version: '3.8'

services:
  tender-backend:
    build: .
    image: tender
    ports: 
      - 8080:8080
    networks:
      - tender-network
    depends_on:
      - db
  
  db:
    image: postgres:13
    restart: always
    networks:
      - tender-network
    environment:
      POSTGRES_DB: tender_managment
      POSTGRES_USER: tender
      POSTGRES_PASSWORD: Vinay@2002
    volumes:
      - tender-db:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  tender-db:

networks:
  tender-network:
